name: Publish to PyPI
on:
  workflow_dispatch:
    inputs:
      checkout:
        description: 'Commit / Branch / Tag / SHA to checkout'
        required: false
        default: ''
        type: string
  # workflow_call:
  #   inputs:
  #     checkout:
  #       description: 'Commit / Branch / Tag / SHA to checkout'
  #       required: false
  #       default: ''
  #       type: string

jobs:
  publish-pypi:
    runs-on: ubuntu-latest

    # environment:
    #   name: pypi
    #   url: https://pypi.org/p/matlab-runtime

    steps:
      - name: Set up Python ${{ inputs.python-version }}
        uses: actions/setup-python@v5

      - name: Check out
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          ref: ${{ inputs.checkout }}

      - name: Install dependencies for building package
        run: python -m pip install --upgrade pip build

      - name: Install distribution 📦
        run: python -m pip install .

      - name: Build distribution 📦
        run: python -m build

      - name: Publish distribution 📦 to Test PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          # password: ${{ secrets.PYPI_TEST_TOKEN }}
          repository-url: https://test.pypi.org/legacy/

      # - name: Publish distribution 📦 to PyPI
      #   uses: pypa/gh-action-pypi-publish@release/v1
      #   with:
      #     password: ${{ secrets.PYPI_TOKEN }}
      #     repository-url: https://upload.pypi.org/legacy/
